### ISSUE TITLE
[Core] After deleting a layer and importing a new layer with the same name a NPE is thrown

### ISSUE THREAD

**Issue by stundzig** [Polymap4/polymap4-core#90] opened 2016-09-26 09:29 UTC
I've deleted a layer ZZZ. After that i've imported new data and used the same name for the new layer ZZZ.

```
java.lang.NullPointerException
    at org.polymap.core.project.ILayer.lambda$0(ILayer.java:56)
    at java.util.Collections$ReverseComparator2.compare(Collections.java:5178)
    at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
    at java.util.TimSort.sort(TimSort.java:220)
    at java.util.Arrays.sort(Arrays.java:1512)
    at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.polymap.core.project.ui.ProjectNodeContentProvider.getChildren(ProjectNodeContentProvider.java:53)
```

**Comment by stundzig** [comment] 2016-09-26 09:47
The problem here is, the NewLayerOperation throws also an exception. But the result is

IMap.layers contains a layer entry, but this is null. So all other services e.g. in ILayer.ORDER_KEY_ORDERING or org.polymap.p4.map.ProjectContentProvider.getElements(Object) are throwing NPEs since the layer is null.

**Comment by fb71** [comment] 2016-10-10 16:58
Duplicate of: [P4] Delete layer (http://github.com/Polymap4/polymap4-p4/issues/issue/93)

**Closed as completed by fb71** 2016-10-10 16:58 UTC
Labels: duplicate
